apiVersion: v1
kind: Service
metadata:
  name: spring-demo
spec:
  selector:
    app: spring-demo
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  selector:
    matchLabels:
      app: spring-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
        - name: spring-demo
          image: spring-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080